services:
  - type: web
    name: cron-generator
    env: node
    buildCommand: npm install && npm install esbuild --platform=linux && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 20